services:
  nh-postgres:
    image: postgres:18.2-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - nh-postgres-data:/var/lib/postgresql/data
    networks:
      - nh-network

  nh-web-api:
    build:
      context: ..
      dockerfile: ./web-api/Dockerfile
    container_name: nh-web-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - nh-postgres
    networks:
      - nh-network

volumes:
  nh-postgres-data:
    
networks:
  nh-network:
    driver: bridge